let data = {
  description: 'Ok',
  code: '200',
  status: true,
  response: {
    drinkingLogReviewList: [
      {
        id: 9,
        drinkingLogId: 9,
        journaling: null,
        childList: [
          {
            id: 28,
            drinkingLogId: 28,
            journaling: null,
            childList: null,
            parentId: 9,
            comment: '12 hello',
            byTherapist: false,
            createdDate: '2020-05-24 11:18:27',
            createdBy: 'Alcohol Management',
            modifiedDate: '2020-05-24 11:18:27',
          },
          {
            id: 27,
            drinkingLogId: 27,
            journaling: null,
            childList: null,
            parentId: 9,
            comment: 'new',
            byTherapist: false,
            createdDate: '2020-05-23 17:35:45',
            createdBy: 'Alcohol Management',
            modifiedDate: '2020-05-23 17:35:45',
          },
          {
            id: 25,
            drinkingLogId: 25,
            journaling: null,
            childList: [
              {
                id: 26,
                drinkingLogId: 26,
                journaling: null,
                childList: null,
                parentId: 25,
                comment: 'ok1,1,1',
                byTherapist: false,
                createdDate: '2020-05-23 17:35:29',
                createdBy: 'Alcohol Management',
                modifiedDate: '2020-05-23 17:35:29',
              },
            ],
            parentId: 9,
            comment: 'ok1.1',
            byTherapist: false,
            createdDate: '2020-05-21 13:29:45',
            createdBy: 'Alcohol Management',
            modifiedDate: '2020-05-21 13:29:45',
          },
          {
            id: 24,
            drinkingLogId: 24,
            journaling: null,
            childList: null,
            parentId: 9,
            comment: 'ok1',
            byTherapist: false,
            createdDate: '2020-05-21 13:29:33',
            createdBy: 'Alcohol Management',
            modifiedDate: '2020-05-21 13:29:33',
          },
          {
            id: 19,
            drinkingLogId: 19,
            journaling: null,
            childList: [
              {
                id: 20,
                drinkingLogId: 20,
                journaling: null,
                childList: [
                  {
                    id: 21,
                    drinkingLogId: 21,
                    journaling: null,
                    childList: [
                      {
                        id: 22,
                        drinkingLogId: 22,
                        journaling: null,
                        childList: [
                          {
                            id: 23,
                            drinkingLogId: 23,
                            journaling: null,
                            childList: null,
                            parentId: 22,
                            comment: 'ok4',
                            byTherapist: false,
                            createdDate: '2020-05-21 13:29:20',
                            createdBy: 'Alcohol Management',
                            modifiedDate: '2020-05-21 13:29:20',
                          },
                        ],
                        parentId: 21,
                        comment: 'ok3',
                        byTherapist: false,
                        createdDate: '2020-05-21 13:29:14',
                        createdBy: 'Alcohol Management',
                        modifiedDate: '2020-05-21 13:29:14',
                      },
                    ],
                    parentId: 20,
                    comment: 'ok2',
                    byTherapist: false,
                    createdDate: '2020-05-21 13:29:08',
                    createdBy: 'Alcohol Management',
                    modifiedDate: '2020-05-21 13:29:08',
                  },
                ],
                parentId: 19,
                comment: 'yes',
                byTherapist: false,
                createdDate: '2020-05-15 06:38:43',
                createdBy: 'Alcohol Management',
                modifiedDate: '2020-05-15 06:38:43',
              },
            ],
            parentId: 9,
            comment: 'ok',
            byTherapist: false,
            createdDate: '2020-05-13 12:26:11',
            createdBy: 'Alcohol Management',
            modifiedDate: '2020-05-13 12:26:11',
          },
          {
            id: 12,
            drinkingLogId: 12,
            journaling: null,
            childList: [
              {
                id: 17,
                drinkingLogId: 17,
                journaling: null,
                childList: null,
                parentId: 12,
                comment: 'Comment1',
                byTherapist: false,
                createdDate: '2020-05-12 15:58:17',
                createdBy: 'Alcohol Management',
                modifiedDate: '2020-05-12 15:58:17',
              },
            ],
            parentId: 9,
            comment: 'Sure, will do that',
            byTherapist: false,
            createdDate: '2020-05-12 15:57:44',
            createdBy: 'Alcohol Management',
            modifiedDate: '2020-05-12 15:57:44',
          },
        ],
        parentId: null,
        comment: 'please fill the logs regularly',
        byTherapist: false,
        createdDate: '2020-05-12 15:54:18',
        createdBy: 'Deepankuamr Kumaran',
        modifiedDate: '2020-05-12 15:54:18',
      },
      {
        id: 8,
        drinkingLogId: 8,
        journaling: null,
        childList: [
          {
            id: 13,
            drinkingLogId: 13,
            journaling: null,
            childList: [
              {
                id: 18,
                drinkingLogId: 18,
                journaling: null,
                childList: null,
                parentId: 13,
                comment: 'Multi 2',
                byTherapist: false,
                createdDate: '2020-05-12 15:58:25',
                createdBy: 'Alcohol Management',
                modifiedDate: '2020-05-12 15:58:25',
              },
            ],
            parentId: 8,
            comment: 'Ok',
            byTherapist: false,
            createdDate: '2020-05-12 15:57:49',
            createdBy: 'Alcohol Management',
            modifiedDate: '2020-05-12 15:57:49',
          },
        ],
        parentId: null,
        comment: 'pleas avoid',
        byTherapist: false,
        createdDate: '2020-05-12 15:53:48',
        createdBy: 'Deepankuamr Kumaran',
        modifiedDate: '2020-05-12 15:53:48',
      },
      {
        id: 7,
        drinkingLogId: 7,
        journaling: null,
        childList: [
          {
            id: 14,
            drinkingLogId: 14,
            journaling: null,
            childList: null,
            parentId: 7,
            comment: 'Ok, Sure',
            byTherapist: false,
            createdDate: '2020-05-12 15:57:56',
            createdBy: 'Alcohol Management',
            modifiedDate: '2020-05-12 15:57:56',
          },
        ],
        parentId: null,
        comment: 'This is not average',
        byTherapist: false,
        createdDate: '2020-05-12 15:53:37',
        createdBy: 'Deepankuamr Kumaran',
        modifiedDate: '2020-05-12 15:53:37',
      },
    ],
    journalingReviewList: [
      {
        id: 11,
        drinkingLogId: null,
        journaling: 1866,
        childList: [
          {
            id: 15,
            drinkingLogId: null,
            journaling: 1866,
            childList: null,
            parentId: 11,
            comment: 'Sure, will do that. Thanks',
            byTherapist: false,
            createdDate: '2020-05-12 15:58:04',
            createdBy: 'Alcohol Management',
            modifiedDate: '2020-05-12 15:58:04',
          },
        ],
        parentId: null,
        comment: 'please fill this',
        byTherapist: false,
        createdDate: '2020-05-12 15:55:02',
        createdBy: 'Deepankuamr Kumaran',
        modifiedDate: '2020-05-12 15:55:02',
      },
      {
        id: 10,
        drinkingLogId: null,
        journaling: 1806,
        childList: [
          {
            id: 16,
            drinkingLogId: null,
            journaling: 1806,
            childList: null,
            parentId: 10,
            comment: 'Sure, will do that. Thanks',
            byTherapist: false,
            createdDate: '2020-05-12 15:58:10',
            createdBy: 'Alcohol Management',
            modifiedDate: '2020-05-12 15:58:10',
          },
        ],
        parentId: null,
        comment: 'Please fill out the Journaling',
        byTherapist: false,
        createdDate: '2020-05-12 15:54:36',
        createdBy: 'Deepankuamr Kumaran',
        modifiedDate: '2020-05-12 15:54:36',
      },
    ],
  },
};
