require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'HealHomeTherapist' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-twilio-video-webrtc', path: '../node_modules/react-native-twilio-video-webrtc'
     permissions_path = '../node_modules/react-native-permissions/ios'
     pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
     pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  
  target 'HealHomeTherapistTests' do
    inherit! :complete
    # Pods for testing
   
    end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

# target 'HealHomeTherapist-tvOS' do
#   # Pods for HealHomeTherapist-tvOS

#   target 'HealHomeTherapist-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# end
