const constants = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  GET_JOURNALING_SUCCESS: 'GET_JOURNALING_SUCCESS',
  SAVE_JOURNALING_SUCCESS: 'SAVE_JOURNALING',
  GET_SUCCESS: 'GET_SUCCESS',
  ERROR: 'ERROR',
  IS_LOADING: 'IS_LOADING',
  CLEAR: 'CLEAR',
};

export default constants;
