const constants = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  GET_JOURNALING_SUCCESS: 'GET_JOURNALING_SUCCESS',
  SAVE_JOURNALING_SUCCESS: 'SAVE_JOURNALING',
  GET_JOURNALING_ID_SUCCESS: 'GET_JOURNALING_ID_SUCCESS',
  GET_SUCCESS: 'GET_SUCCESS',
  GET_ALL_REQUESTED_SESSION_SUCCESS: 'GET_ALL_REQUESTED_SESSION_SUCCESS',
  REQUEST_SESSION_SUCCESS: 'REQUEST_SESSION_SUCCESS',
  UPDATE_REQUEST_SESSION_SUCCESS: 'UPDATE_REQUEST_SESSION_SUCCESS',
  GET_REQUESTED_SESSION_BY_ID_SUCCESS: 'GET_REQUESTED_SESSION_BY_ID_SUCCESS',
  GET_ALL_THERAPISTS_SUCCESS: 'GET_ALL_THERAPISTS_SUCCESS',
  UPCOMING_SESSION_SUCCESS: 'UPCOMING_SESSION_SUCCESS',
  GET_ALL_HANDOUTS_SUCCESS: 'GET_ALL_HANDOUTS_SUCCESS',
  GET_ALL_THERAPISTS_REVIEW_SUCCESS: 'GET_ALL_THERAPISTS_REVIEW_SUCCESS',
  GET_ALL_ASSESSMENT_SUCCESS: 'GET_ALL_ASSESSMENT_SUCCESS',
  GET_ASSESSMENT_BY_ID_SUCCESS: 'GET_ASSESSMENT_BY_ID_SUCCESS',
  ERROR: 'ERROR',
  IS_LOADING: 'IS_LOADING',
  CLEAR: 'CLEAR',
  CLEAR_SESSION_BY_ID: 'CLEAR_SESSION_BY_ID',
};

export default constants;
